apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: default
type: Opaque
data:
    secret_password: ENC[AES256_GCM,data:8kRnMOEFPrghx+kyLZEmFGa/oygnwHtGzbM22Q==,iv:7xdUtWunbKcN7Hg3cqvcXp0jHvXizTk7XWzXGh7+/oM=,tag:ZlEd9X/WGDEhorArfvYsZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c620pnquawnws5n8sn0jd59le8u7s7trs03gyxeayy7gx5nkyg4q059xyh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRm96cm50MUtqdlhuN1pl
            SmIzQXdsd3RneUdIemVWUkFDYnRDTWc2M2tRCkptTmVySWUzYS9oR2NvdnJpaU1T
            Y2xZNWsvSklaWnV2MzhxYUhES1hSdW8KLS0tIHN3eWp3TFF2andVa2VuV01hVXlI
            aStOQTBpaHp6VjRPWk1EdXBISjkvM0EKd8Lg9UQ5n+Vrp8tIi3RtcY9xnmymG7Hf
            McItjDMrAoMbB1k9jvB6ON8JihbEhJxQatrnKZ0m+Xh0XesljoNujA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T21:09:41Z"
    mac: ENC[AES256_GCM,data:mWUK193ae/Cs6vLeYqxphrUdv8IwTRA0MMSyv14biPpLR1Febur48aIf/kYAG2t+PaS0axkmGura/B+s+X7OKUeIg+KOLUJeq0GDhvG1ZDHu9udpn0PBq0zsgOihNVSnCqHsbFoRHZ2JLF7O75gC1I0ZbpIIr+DDJ4fFoctxxVI=,iv:LByN2Wr3jmi3X0VlHPb/IvOV2RzmDjTLh13Y1WcaEgA=,tag:A5n2reZGIv4QA6P795492A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
